apiVersion: v1
kind: Service
metadata:
  name: lake-redirector-xrootd
  namespace: cms-admin
spec:
  selector:
    k8s-app: lake-redirector
  type: NodePort
  ports:
  - name: condor
    port: 1094
    nodePort: 31620
    protocol: TCP
    targetPort: 1094

