apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: cms-xrootd-data-lake-origin-caltech
  name: cms-xrootd-data-lake-origin-caltech
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cms-xrootd-data-lake-origin-caltech
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: cms-xrootd-data-lake-origin-caltech
    spec:
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/stashcache
        operator: Exists
      initContainers:
      - command: ["sh", "-c", "chown -R 10940:10940 /xorigin/* "]
        image: busybox
        imagePullPolicy: Always
        name: chowndata
        volumeMounts:
        - mountPath: /xorigin
          name: localroot
        - mountPath: /xorigin/data1
          name: data1
        - mountPath: /xorigin/data2
          name: data2
        - mountPath: /xorigin/data3
          name: data3
        - mountPath: /xorigin/data5
          name: data5
        - mountPath: /xorigin/data6
          name: data6
        - mountPath: /xorigin/data7
          name: data7
        - mountPath: /xorigin/data8
          name: data8
        - mountPath: /xorigin/data9
          name: data9
        - mountPath: /xorigin/data10
          name: data10
        - mountPath: /xorigin/data11
          name: data11
        - mountPath: /xorigin/data12
          name: data12
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s1-pb10.ultralight.org
      containers:
      - env:
        - name: XC_ROOTDIR
          value: /xorigin
        - name: XC_MULTI_DISK
          value: 'true'
        - name: XC_RESOURCENAME
          value: USDataLake
        - name: XC_LOCAL_REDIRECTORS
          value: '10.106.4.208:1095'
        image: opensciencegrid/xrootd-standalone:fresh
        ports:
         - containerPort: 1094
           hostPort: 1094
        imagePullPolicy: Always
        name: cms-xrootd-data-lake-origin-caltech
        resources:
           limits:
              memory: 30Gi
              cpu: 4
           requests:
              memory: 20Gi
              cpu: 4
        volumeMounts:
        - mountPath: /etc/xrootd/config.d/95-local-ucsd.cfg
          name: config95
          subPath: 95-local-ucsd.cfg
        - mountPath: /etc/grid-security/hostcert.pem
          name: certificate
          readOnly: true
          subPath: hostcert.pem
        - mountPath: /etc/grid-security/hostkey.pem
          name: hostkey
          readOnly: true
          subPath: hostkey.pem
        - mountPath: /xorigin
          name: localroot
        - mountPath: /xorigin/data1
          name: data1
        - mountPath: /xorigin/data2
          name: data2
        - mountPath: /xorigin/data3
          name: data3
        - mountPath: /xorigin/data5
          name: data5
        - mountPath: /xorigin/data6
          name: data6
        - mountPath: /xorigin/data7
          name: data7
        - mountPath: /xorigin/data8
          name: data8
        - mountPath: /xorigin/data9
          name: data9
        - mountPath: /xorigin/data10
          name: data10
        - mountPath: /xorigin/data11
          name: data11
        - mountPath: /xorigin/data12
          name: data12
      #hostNetwork: true
      restartPolicy: Always
      volumes:
      - name: data1
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-1
      - name: data2
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-2
      - name: data3
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-3
      - name: data4
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-4
      - name: data5
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-5
      - name: data6
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-6
      - name: data7
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-7
      - name: data8
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-8
      - name: data9
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-9
      - name: data10
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-10
      - name: data11
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-11
      - name: data12
        persistentVolumeClaim:
          claimName: pvc-xrootd-data-lake-origin-caltech-k8s1-pb10-ultralight-org-persistent-12
      - name: localroot
        hostPath:
          path: /xorigin-root
          type: Directory
      - configMap:
          defaultMode: 420
          items:
          - key: 95-local-ucsd.cfg
            path: 95-local-ucsd.cfg
          name: ucsdoriginconfig
        name: config95
      - name: certificate
        secret:
          secretName: caltech-origin-certs
          items:
          - key: hostcert
            path: hostcert.pem
          defaultMode: 0600
      - name: hostkey
        secret:
          secretName: caltech-origin-certs
          items:
          - key: hostkey
            path: hostkey.pem
          defaultMode: 0600